POST https://soulssfg.wixsite.com/_api/wix-forms/v1/submit-form
Content-Type: application/json
Authorization: rxOaa8kECT-a_R_fx9vquN5kN6g19E6jt_V_NLy44gE.eyJpbnN0YW5jZUlkIjoiYTk5NGEyOTQtNWE1OS00ODQ4LThiYzYtODRlYTU2OWI2YzNkIiwiYXBwRGVmSWQiOiIxNGNlMTIxNC1iMjc4LWE3ZTQtMTM3My0wMGNlYmQxYmVmN2MiLCJtZXRhU2l0ZUlkIjoiNzY5MGI2YTEtNDc3My00OTZjLWIwZWYtODMyMjVlYjVkODI4Iiwic2lnbkRhdGUiOiIyMDIyLTA5LTI0VDA3OjI0OjE2LjQxMloiLCJkZW1vTW9kZSI6ZmFsc2UsIm9yaWdpbkluc3RhbmNlSWQiOiI4N2ViZWQ2Zi1lZmMzLTRlNTAtYTE1OC01NDRjYjY2NDE4ZDAiLCJhaWQiOiI5YWE2NGVkNy1iZTg3LTQ5ZmEtOGZjYy1jOGZjNGNjYzg5NjgiLCJiaVRva2VuIjoiZGYwNDE0MzUtMWQyYS0wMTI0LTNiMjktMDdjODA4MmViNDE1Iiwic2l0ZU93bmVySWQiOiJkZTQ5YWI1NC1hNTc5LTRhMDUtODE3OC0wYWY1ZTRkMTUzY2UifQ

{
  "formProperties": {
    "formName": "Contact",
    "formId": "comp-kowtyen4"
  },
  "emailConfig": {
    "sendToOwnerAndEmails": {
      "emailIds": []
    }
  },
  "fields": [
    {
      "fieldId": "comp-kowtyens1",
      "firstName": {
        "value": "testName"
      }
    },
    {
      "fieldId": "comp-kowtyeo31",
      "lastName": {
        "value": "testLastName"
      }
    },
    {
      "fieldId": "comp-kowtyeo52",
      "email": {
        "value": "test@test.sum"
      }
    },
    {
      "fieldId": "comp-kowtyeo8",
      "additional": {
        "value": {
          "string": "TEST"
        }
      }
    },
    {
      "fieldId": "comp-kowtyeoa1",
      "additional": {
        "value": {
          "string": "0a4test"
        }
      }
    }
  ]
}